default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['POSTGRES_USERNAME'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>

test:
  adapter: sqlite3
  database: db/test.sqlite3
  host: localhost

development:
  adapter: sqlite3
  database: db/development.sqlite3
  host: localhost

production:
  <<: *default
  adapter: postgresql
  encoding: unicode

staging:
  <<: *default
  adapter: postgresql
  encoding: unicode
